### PR TITLE
Add "u0069" glif for "lowercase i" style

### PR DESCRIPTION
**Pull request by tri-nga**
Alternative style for "u0069" glif.

### CODE REVIEW

**Comment by chrissimpkins** [comment]
Looks great @dok42!  Thanks for adding these.  A couple of requests.

1) Can I ask you to modify the directory path to the following:

```
u0069-slab
```

The Unicode code point defines the glyph (i.e. lower case i) so this is not necessary in the path naming scheme.  The word should provide details about how the shape changes vs. the default in the Hack sets.

2) Confirming that you have looked at horizontal positioning of the glyph vs. other glyphs with these changes.  Have you built a set that includes this new shape and are we ok with how it is aligned with other glyphs if users build new sets with it?  Our design target goals are listed here https://github.com/source-foundry/Hack/blob/master/CONTRIBUTING.md#design-targets.  These are the sizes and bodies of text that we target with this set of fonts.

Push a new commit with the above changes are we should be all set to merge this!

**Comment by chrissimpkins** [comment]
Also, any new commits that you push to your remote repository will automatically show up in this pulll request.  No need to do anything further.  Just keep adding changes as you have been doing and we merge when it is ready on your end.

**Comment by tri-nga** [comment]
@chrissimpkins 
Point 2:
My approach to the glyph position, is visual.
Here are the steps I've done to make these .glif.

Step 1:
I did open the Hack-Regular.ufo in Fontforge.
Step 1

Step 2:
From File --> Open
I did open the DejavuSansMono.sdf source file, and I've made a Font Compare
Step 2

Step 3:
Done this, when I open the single glyph, the **i** of Hack Regular in this case, I have the Dejavu **i** shape in green as guide in background.
Step 3

Doing this I can see the differences between the glyph.
For this glyph I just copy-pasted the base **i** from DejavuSansMono and aligned the dot. 

Honestly I don't know what all those external infinite lines are, they look like guides.

=====
About other commits.
For the other .glif, have I to create separated branch, add files, commit, push and then do another pull request ? Right ?

**Comment by chrissimpkins** [comment]
Excellent, sounds good!

> About other commits.
For the other .glif, have I to create separated branch, add files, commit, push and then do another pull request ? Right ?

As soon as I am finished with the updates (including the addition of the images on a README for this merge) you can execute the following command on your master branch:

```
git pull https://github.com/source-foundry/alt-hack.git
```

Then branch from your master and start the process again.  Your master will remain up to date with the changes upstream with that approach.  Once this is merged, it is ok to delete the branch you used for this pull request.

**Comment by chrissimpkins** [comment]
@dok42 we're all set in master.  you can view the new readme in your directory.  ready for the next PR whenever you are ready.

**Pull request merged**
