### PR TITLE
Add magic CL script.

### PR DESCRIPTION
**Pull request by equwal**
This adds a new script written in Common Lisp for generating fonts. Includes help, format options, and a custom language for defining your permutations.

It works by using the Hack project as a submodule. See the updated README.md for examples and usage.

It has a few features to help unwitting users:
- Fails nicely for bad specifications (eg. two different variants of zero).
- Has a help that shows up.
- Just specify which variants you want from the list.

Addresses https://github.com/source-foundry/alt-hack/issues/43

### CODE REVIEW

**Comment by equwal** [comment]
This has been here awhile.

Is there anything I can do to help it along? Perhaps it must be written in a more ubiquitous language like Perl to be accepted?

**Comment by chrissimpkins** [comment]
This is great and an approach like this is definitely desirable but I won't be able to review or maintain Lisp sources. I hate to have you refactor all of this work.  Will you maintain this in a downstream and we can point to it from the README?

**Comment by equwal** [comment]
> This is great and an approach like this is definitely desirable but I won't be able to review or maintain Lisp sources. I hate to have you refactor all of this work. 

I chose lisp because it is a powerful language for solving complex problems. It would have been really hard to do it in a shell script without making a prototype like this first.

> Will you maintain this in a downstream and we can point to it from the README?

Yes, I will take care of my baby.

**Comment by chrissimpkins** [comment]
Don't take this the wrong way.  I trust your opinion that this may be a good approach.  I don't know Lisp.  It is really as simple as that.  :)

**Comment by equwal** [comment]
I just saw the pull request from @barrycohen, and I think that is going to be the way forward.

**Pull request closed without merging**
